export const NODE_PROPS = [
  'id',
  'type',
  'name',
  'visible',
  'locked',
  'opacity',
  'blendMode',
  'isMask',
  'maskType',
  'clipsContent',
  'x',
  'y',
  'width',
  'height',
  'rotation',
  'relativeTransform',
  'absoluteTransform',
  'constraints',
  'layoutAlign',
  'layoutGrow',
  'layoutMode',
  'layoutPositioning',
  'layoutWrap',
  'primaryAxisAlignItems',
  'counterAxisAlignItems',
  'primaryAxisSizingMode',
  'counterAxisSizingMode',
  'itemSpacing',
  'counterAxisSpacing',
  'paddingTop',
  'paddingRight',
  'paddingBottom',
  'paddingLeft',
  'cornerRadius',
  'topLeftRadius',
  'topRightRadius',
  'bottomLeftRadius',
  'bottomRightRadius',
  'strokesIncludedInLayout',
  'fills',
  'strokes',
  'strokeWeight',
  'strokeAlign',
  'strokeJoin',
  'strokeCap',
  'strokeMiterLimit',
  'dashPattern',
  'effects',
  'effectStyleId',
  'fillStyleId',
  'strokeStyleId',
  'textStyleId',
  'characters',
  'fontSize',
  'fontName',
  'textCase',
  'textDecoration',
  'textAlignHorizontal',
  'textAlignVertical',
  'textAutoResize',
  'lineHeight',
  'letterSpacing',
  'paragraphSpacing',
  'paragraphIndent',
  'listSpacing',
  'hyperlink',
  'maxLines',
  'exportSettings',
  'componentId',
  'componentProperties',
  'boundVariables'
] as const;

export const PLUGIN_MESSAGES = {
  EXPORT_PAYLOAD: 'export-payload',
  EXPORT_DONE: 'export-done',
  EXPORT_FAILED: 'export-failed'
} as const;
